security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'plaintext'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/logout, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/products, roles: PUBLIC_ACCESS, methods: [GET, POST, PUT, DELETE] }
        - { path: ^/api/users, roles: PUBLIC_ACCESS, methods: [GET, POST, PUT, DELETE] }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
