<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRBThoxY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRBThoxY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRBThoxY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRBThoxY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRBThoxY\App_KernelDevDebugContainer([
    'container.build_hash' => 'RBThoxY',
    'container.build_id' => 'cf4499b4',
    'container.build_time' => 1718072137,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRBThoxY');
